### ISSUE TITLE
Gardar o job.id como _id da coleccion

### ISSUE THREAD

**Issue by alambike** [prefapp/catro-eixos-jobs#3]
Tal como facíamos en eixo-queue:

https://github.com/frmadem/eixo_queue/blob/master/lib/Eixo/Queue/MongoDriver.pm

De esta forma se aproveita o indexado automático do campo _id, aparte de ser a clave primaria de toda a colección. Senon se pode repetir e ademáis, cando empece a crece vai a ralentizar as busquedas.ç

**Comment by frmadem** [comment]
Corregido y actualizado en este [commit](https://github.com/prefapp/catro-eixos-jobs/commit/522c27cc737adb6f40fc14b38be5f9040d0d8d29)
